### get book
GET http://localhost:8080/book/book-1

### get author
GET http://localhost:8080/author/author-1

### RSocket request
RSOCKET findBook
Host: ws://localhost:8080/rsocket
Content-Type: application/json

"book-1"

### GraphQL over HTTP
GRAPHQL http://localhost:8080/graphql
Content-Type: application/graphql

query findBook {
    findBook(id: "book-1") { id name }
}

### GraphQL over WebSocket
GRAPHQL ws://localhost:8080/graphql
Content-Type: application/graphql

query findBook{
    findBook(id: "book-1") { id name }
}

### GraphQL over RSocket
GRAPHQL rsocketws://localhost:8080/rsocket/graphql
Content-Type: application/graphql

query findBook{
    findBook(id: "book-1") { id name }
}

