### get book
GET http://localhost:8080/book/book-1

### get author
GET http://localhost:8080/author/author-1

### graphql query
POST http://localhost:8080/graphql
Content-Type: application/json

< ./graphql-query.json

### RSocket request
RSOCKET findBook
Host: ws://localhost:8080/rsocket
Content-Type: application/json

"book-1"

### GraphQL over RSocket
RSOCKET graphql
Host: ws://localhost:8080/rsocket
Content-Type: application/json

{
  "query": "{ findBook(id: \"book-1\") { id name } }"
}
